### ISSUE TITLE
Feature Request: Pre-route hook

### ISSUE THREAD

**Issue by byronferguson** [lukepighetti/fluro#102]
Unless I've missed the ability, it would be convenient to have a pre-route hook for individual routes and for all routes.

If possible.

**Comment by lukef** [comment]
This is coming in 2.0!

**Comment by GregorySech** [comment]
Kinda off-topic but can `Filter` be used for route guarding?

**Comment by lukef** [comment]
Yep! That's the intention. A Filter can either proceed, stop or error. So, if you wanted to do an auth guard you can "stop" and return the widget asking you to log in.

**Comment by rlee1990** [comment]
Is there a time line for this?

**Comment by zero7u** [comment]
When will ```fluro 2.0``` come? we also need the feather, thx bro~

**Comment by lukepighetti** [comment]
Duplicate of https://github.com/lukepighetti/fluro/issues/112
