### ISSUE TITLE
How to pass a map (instance of SomeObject) in fluro?

### ISSUE THREAD

**Issue by hkmsadek** [lukepighetti/fluro#104]
I am trying to pass some map data but it always sends string. Is there anyways that I can send map data?
Thank you.

**Comment by MahdiPishguy** [comment]
+1

**Comment by nousath** [comment]
i have same issue

**Comment by wenboLee** [comment]
+1
abandon fluro~ 🤨
user `Navigator.push`

**Comment by pdliuw** [comment]
> I am trying to pass some map data but it always sends string. Is there anyways that I can send map data?
> Thank you.

Airoute supports this feature (Airoute : https://github.com/pdliuw/airoute)

**Comment by pdliuw** [comment]
> i have same issue

Airoute supports this feature (Airoute : https://github.com/pdliuw/airoute)

**Comment by MahdiPishguy** [comment]
> 
> 
> > i have same issue
> 
> Airoute supports this feature (Airoute : https://github.com/pdliuw/airoute)

it seems, it doesn't have any English document

**Comment by pdliuw** [comment]
> > > i have same issue
> > 
> > 
> > Airoute supports this feature (Airoute : https://github.com/pdliuw/airoute)
> 
> it seems, it doesn't have any English document

It will support in half an hour

**Comment by misterfourtytwo** [comment]
> I am trying to pass some map data but it always sends string. Is there anyways that I can send map data?
>

You could send and recieve arguments using ordinary 
```Navigator.of(context).push('/route', arguments='your object here')```
 and then get them with
```ModalRoute.of(context).settings.arguments as (your object type)```

**Comment by marceloreis13** [comment]
Migrating to @pdliuw  Airoute right now! 😉
This lib (fluro) seems to be abandoned 😒

**Comment by MahdiPishguy** [comment]
> 
> 
> Migrating to @pdliuw Airoute right now! wink
> This lib (fluro) seems to be abandoned unamused

I think `Sailor` is better than `Airoute`

**Comment by marceloreis13** [comment]
> > Migrating to @pdliuw Airoute right now! wink
> > This lib (fluro) seems to be abandoned unamused
> 
> I think `Sailor` is better than `Airoute`

Thanks @MahdiPishguy `Sailor` is more complete than `Airoute`

**Comment by huangsir0** [comment]
`   while(true){
      wanted+=1;
    }`

**Comment by dmlzj** [comment]
You can see here, I have solved it!
https://github.com/dmlzj/fluro

**Comment by lukepighetti** [comment]
You can now pass custom RouteSettings with arguments https://github.com/lukepighetti/fluro/commit/acfa58054765484489e49fd1f74a45002825fdcb
