### ISSUE TITLE
Update route params without navigating

### ISSUE THREAD

**Issue by smkhalsa** [lukepighetti/fluro#106]
I have an app with a PageView, and I'd like to adjust the route as I swipe through each page (for example: `"myScreen/:pageIndex"`). I can't find a way to update the route without navigating to a new screen. I've tried the `replace: true` parameter of navigateTo, but it still animates to another instance of the same page.

**Comment by willcalderbank** [comment]
This would be a great feature for us as well. We would like the state of the page to be represented in the URL for deep linking. Thanks

**Comment by lukepighetti** [comment]
Closing this because we're preparing for a major overhaul in `fluro 2.0` when we migrate to the new Pages / Navigator 2.0 API and I suspect the scope of this issue will change as a result. Please reopen if needed.
