### ISSUE TITLE
Route Filter / Guards

### ISSUE THREAD

**Issue by dt-ap** [lukepighetti/fluro#112]
Is there any estimation when fluro 2.0.0 will be released?? I read that it will have **Filter** for routes. Would love to have route-based filtering especially for authentication.

**Comment by lukepighetti** [comment]
This is now the tracking issue for route filters and guards.

**Comment by rlee1990** [comment]
@lukepighetti any update when this will use navigator 2.0 and navigator restoration?

**Comment by lukepighetti** [comment]
Please refer to this discussion https://github.com/lukepighetti/fluro/discussions/213

**Comment by lukepighetti** [comment]
@rlee1990 I did a quick search and can't find anything about navigator restoration, can you collect some info and make a new issue?
