### ISSUE TITLE
Support for accessing Routing stack

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [lukepighetti/fluro#115]
Hi, I looked through the docs briefly and didn't see if it was supported, but is there a way to see the route stack and history? In my current project which uses the default Navigator, I want to say something like:
```dart
if(Navigator.of(context).containsRoute(ModalRoute.withName('/'))){
   Navigator.of(context).popUntil(ModalRoute.withName('/'));
}
else {
  Navigator.of(context).popAndPushNamed('/'));
}
```
except this isn't possible currently. Can we have the option to work with the Router data with Fluro?

**Comment by misterfourtytwo** [comment]
u could simply check this via [ModalRoute.of(context).isFirst](https://api.flutter.dev/flutter/widgets/ModalRoute/isFirst.htm)l or [ModalRoute.of(context).settings.name == '/'](https://api.flutter.dev/flutter/widgets/RouteSettings/name.html)

**Comment by lukepighetti** [comment]
Closing because there is nothing actionable.
