### ISSUE TITLE
how can i pass class data?

### ISSUE THREAD

**Issue by MahdiPishguy** [lukepighetti/fluro#120]
instead of making Map or using variable of class fields value i want to pass class to another screen with the library, how can i do?

**Comment by beilunyang** [comment]
I met the same problem. How did you solve it

**Comment by wangfeng211** [comment]
I met the same problem. How did you solve it？

**Comment by dmlzj** [comment]
You can see here, I have solved it!
https://github.com/dmlzj/fluro

**Comment by lukepighetti** [comment]
You can now pass custom RouteSettings acfa58054765484489e49fd1f74a45002825fdcb
