### ISSUE TITLE
BuildContext null  for HandlerType.function

### ISSUE THREAD

**Issue by KieranLafferty** [lukepighetti/fluro#125]
**Describe the bug**
BuildContext is coming through null in the following handler:

```
  static Handler _storeHandler = Handler(
    type: HandlerType.function,
    handlerFunc: (
      BuildContext context,
      Map<String, dynamic> params,
    ) {
      final tabBloc = Provider.of<ApplicationTabBloc>(context);
      tabBloc.dispatch(
        ApplicationTabEventUpdate(
          tab: ApplicationTab.store,
        ),
      );
    },
  );

   ...

   ApplicationRouter.router.define(
      "store",
      handler: _storeHandler,
    );
```

Error does not occur if I change from `HandlerType.function` to `HandlerType.route`

**To Reproduce**
1. Navigate using `Navigator.pushNamed(context, 'store')`
2. Breakpoint on line  `final tabBloc = Provider.of<ApplicationTabBloc>(context);`
3. Observe via inspector that context is null
4. Provider fails to grab the bloc and app throws exception for calling Provider on null

**Expected behavior**
I would have expected that context would be non-null for both `HandlerType.function` and `HandlerType.route`

**Desktop (please complete the following information):**
 -  iOS

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: iOS 13

**Additional context**

**Comment by KieranLafferty** [comment]
Just to follow up on this, noticed that it works correctly when calling via 

```
ApplicationRouter.router.navigateTo(context, '/store');
```

But fails using 

```
Navigate.pushNamed(context, '/store')
```

**Comment by pdliuw** [comment]
> Just to follow up on this, noticed that it works correctly when calling via
> 
> ```
> ApplicationRouter.router.navigateTo(context, '/store');
> ```
> 
> But fails using
> 
> ```
> Navigator.pushNamed(context, '/store')
> ```

Airoute supports this feature and need not BuildContext object (Airoute : https://github.com/pdliuw/airoute)

**Comment by lukepighetti** [comment]
Closing because there is nothing actionable

**Comment by github-fuer-spam** [comment]
I would like to come back to this issue. Perhaps there is a misunderstanding, but if I try in flutter web to use the function handler with setting a link in the addressbar of the browser, I have a null-context. Is this intentionally so? 

`static Handler userHandler = Handler(
    type: HandlerType.function,
    handlerFunc: (
        BuildContext? context,
        Map<String, List<String>> params,
        ) {
      String? idParam = params['id']?.first;
      int deviceId;
      idParam != '' ? deviceId = int.parse(idParam!): deviceId = 0;
      if(Authentication.isAuthenticated) {
        // context is null here
        print(context.toString());`
