### ISSUE TITLE
Handle function call many times

### ISSUE THREAD

**Issue by wemdeveloper** [lukepighetti/fluro#127]
**Describe the bug**

**To Reproduce**
1. Clone Example from repository
2. Add print add rootHandler
3. My Project have same issue

![Screen Shot 2019-10-01 at 1 48 56 PM](https://user-images.githubusercontent.com/27657751/65940411-a9e02100-e452-11e9-979b-a90f338473d3.png)
![Screen Shot 2019-10-01 at 1 52 04 PM](https://user-images.githubusercontent.com/27657751/65940419-aea4d500-e452-11e9-8cb2-5fa27f880533.png)

**Comment by lukepighetti** [comment]
Cannot reproduce
