### ISSUE TITLE
Does it support `popUtil` ?

### ISSUE THREAD

**Issue by Moosphan** [lukepighetti/fluro#133]
We often have this usual requirement in apps, if supports, can you give an example in future? thanks~

**Comment by dongjianxiong** [comment]
like A-(push)>B-(push)>C-(push)>D,  now in D,  and then you need podUntil(B) to go back to B

**Comment by Moosphan** [comment]
@dongjianxiong yeah, like this situation.

**Comment by EightMinuteYouth** [comment]
We have also encountered, may I ask the current support? thanks~

**Comment by pdliuw** [comment]
> @dongjianxiong yeah, like this situation.

Airoute Support this feature (Airoute:https://github.com/pdliuw/airoute)

**Comment by loveway** [comment]
when it will support?

**Comment by markdashi** [comment]
> like A-(push)>B-(push)>C-(push)>D, now in D, and then you need podUntil(B) to go back to B

u can use Navigator.of(context).popUntil solve 

eg: Navigator.of(context).popUntil((route) => route.settings.name.startsWith("/B"))

**Comment by markdashi** [comment]
> like A-(push)>B-(push)>C-(push)>D, now in D, and then you need podUntil(B) to go back to B

u can use Navigator.of(context).popUntil solve

if you not transfer parameters ，u can use Navigator.popUntil(context, ModalRoute.withName("/home"));

commonly we transfer parameters, above method not work , we must use 

eg: Navigator.of(context).popUntil((route) => route.settings.name.startsWith("/B")) .

it's works for me.

**Comment by lukepighetti** [comment]
This is covered by the Navigator 1.0 API. See `Navigator.of(context).popUntil`
