### ISSUE TITLE
ArgumentError (Invalid argument(s): Illegal percent encoding in URI) 中文兼容性问题 

### ISSUE THREAD

**Issue by LZHS** [lukepighetti/fluro#134]
tree.dart  226 
 
描述， 如果参数为中文这里会报错，如图：
![avatar](https://github.com/LZHS/MarkDownWords/blob/master/images/7C882A8D-F321-4AB4-95EF-C11582F3F2ff.jpg?raw=true)

建议修改：

![avatar](https://github.com/LZHS/MarkDownWords/blob/master/images/15746731703731.png?raw=true)

**Comment by Lcccocoa** [comment]
String encodeRouteParam() {
    return Uri.encodeComponent(this);
  }
  String decodeRouteParam() {
    return Uri.decodeComponent(this);
  }

**Comment by TomarsNi** [comment]
var param = Uri.encodeComponent(“中文”);
  这样处理一下就行了

**Comment by LazyDev96** [comment]
any progress?

**Comment by lukepighetti** [comment]
Non-roman characters are wontfix for `1.x.x` unless someone can provide a PR with test case.
