### ISSUE TITLE
No handler when multi matches

### ISSUE THREAD

**Issue by crazygo** [lukepighetti/fluro#135]
**Describe the bug**
route 1: /abc/:p1
route 2:/abc/:p2/edit

Fluro can't find handler for the second router

**Additional context**
for that line https://github.com/theyakka/fluro/blob/15363723607d3be9e03e04d8c50d058f78fa647c/lib/src/tree.dart#L161

I think all the matchers needs to  check ,not only the first one. If their are multi matchers, you convert Map to List , the order is not defined , so sometimes return right ,sometimes return null

**Comment by lukepighetti** [comment]
This is a wontfix for `1.x.x`. As a note, you might try changing the order in which you define your routes.
