### ISSUE TITLE
Navigating Problem

### ISSUE THREAD

**Issue by deshario** [lukepighetti/fluro#139]
```Application.router.navigateTo(context, "/sample", transition: TransitionType.fadeIn); ```

![routes](https://user-images.githubusercontent.com/11426727/71501646-3d808c80-289e-11ea-85bc-dd1955cbd538.png)

![handler](https://user-images.githubusercontent.com/11426727/71501792-fe9f0680-289e-11ea-81dd-a1637718cc5f.png)

![Application](https://user-images.githubusercontent.com/11426727/71501826-34dc8600-289f-11ea-9bbe-4e2fb6a22b17.png)

![androidStudio](https://user-images.githubusercontent.com/11426727/71501588-eaa6d500-289d-11ea-9a70-e669d0c8740f.png)

![fluro](https://user-images.githubusercontent.com/11426727/71501498-93086980-289d-11ea-9387-a3ec708b6617.png)

What is missing from me .. Can u please help me figure it out. Thanks

**Comment by ck86** [comment]
You should start your widget tree with a MaterialApp widget.

**Comment by lukepighetti** [comment]
Closing because there's nothing actionable.
