### ISSUE TITLE
Deeplink in example does not work

### ISSUE THREAD

**Issue by theobouwman** [lukepighetti/fluro#14]

**Comment by lukef** [comment]
There are a couple of open issues in the flutter project regarding deep linking so we will have to wait for those to progress.

**Comment by caioiglesias** [comment]
Is this the "mess" ticket: https://github.com/flutter/flutter/issues/11490 ?

**Comment by lukef** [comment]
The flutter team is currently working on improvements to `Navigator`  which will include the ability to do deep linking. At this point its a wait and see kind of deal. It is best to ask on Gitter what the status is.

**Comment by superciccio** [comment]
What's the status on this one, are we still waiting ? :)

**Comment by spkingr** [comment]
So right now how to do navigation in nested routers or deep links like these pages:
`'/', `/page/`, '/page/nested_page' `
Thanks!

**Comment by ened** [comment]
Should this project integrate https://github.com/avioli/uni_links for this?

**Comment by lukef** [comment]
I'll take a look

**Comment by nurseiit** [comment]
I'm planning on using Fluro with Firebase Dynamic Links to handle deeplinks.
Haven't yet tested it, does anyone know anything regarding this?

**Comment by lukepighetti** [comment]
Closing due to a combination of stale, wontfix, out of scope, etc etc.
