### ISSUE TITLE
Transition Speed

### ISSUE THREAD

**Issue by EdgarSantiago93** [lukepighetti/fluro#143]
Hello!
Great package, i use it on all my projects, it has evolved a lot.

i think it'd be a great addition if you could add a transition speed option to the  `define` method
currently i have to copy and alter the whole thing only to alter the speed.

thank you!

**Comment by lukepighetti** [comment]
Resolved by https://github.com/lukepighetti/fluro/commit/76d9a0e950d65e702fdd813854d97447979a7744
