### ISSUE TITLE
TransitionType.none

### ISSUE THREAD

**Issue by jasonspick** [lukepighetti/fluro#151]
Simple feature request. No animated transition type as an option

**Comment by SkyeNygaard** [comment]
The way I dealt with this was setting transition time to none 
`router.navigateTo(context, routeString,
                transition: TransitionType.fadeIn,
                transitionDuration: Duration(milliseconds: 0));`
 using the router. Doesn't let you use the Navigator class though, so I agree this would be nice to add.

**Comment by fifersheep** [comment]
Agree that this would be a nice addition to ignore transitions. I have achieve this though with a custom, no-op transition:

```dart
router.navigateTo(
    context,
    path,
    transition: TransitionType.custom,
    transitionBuilder: (_, __, ___, child) => child,
);
```

**Comment by lukepighetti** [comment]
Resolved by https://github.com/lukepighetti/fluro/commit/16a54391479468f2e323a13a1932b9dc9a85a4ec
