### ISSUE TITLE
Add a new PageRoute (NoAnimRouteBuilder)to RouteCreator

### ISSUE THREAD

**Issue by philos3** [lukepighetti/fluro#160]
I think NoAnimRouteBuilder is useful,  you should consider adding it.

static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case RouteName.splash:
        return NoAnimRouteBuilder(SplashScreenPage());
      case RouteName.register:
        return CupertinoPageRoute(builder: (_) => RegisterPage());
   }
}

**Comment by lukepighetti** [comment]
Resolved by https://github.com/lukepighetti/fluro/commit/16a54391479468f2e323a13a1932b9dc9a85a4ec
