### ISSUE TITLE
No result possible to be returned by `pop()`

### ISSUE THREAD

**Issue by boylenssen** [lukepighetti/fluro#164]
when using `Router.pop()` I cannot add a result which can be send back to the page `push()`'ing the page.

`Navigator.pop()` has an optional argument for this. Why is this not available for `Router.pop()`?

![image](https://user-images.githubusercontent.com/5054262/78763850-fb2f1700-7985-11ea-8bc2-e9897808bae8.png)

**Comment by lukepighetti** [comment]
Resolved by https://github.com/lukepighetti/fluro/commit/157fca6c6816d12db6095e6a4bc70914b1f13348
