### ISSUE TITLE
Browser back and forward button not working with flutter for web

### ISSUE THREAD

**Issue by amal-chacko-7** [lukepighetti/fluro#165]
Back button is working when I use pushNamed method and not working with pushReplacementNamed method. Forward button is not working with either of the method.

**Comment by lukepighetti** [comment]
Fluro 1.x.x will not support Flutter Web. When we migrate to the new Pages / Navigator 2.0 API we will be adding support for Flutter Web. Please see https://github.com/lukepighetti/fluro/issues/184#issuecomment-708659225 for more information.

**Comment by lukepighetti** [comment]
Note: latest commit does work on web with back button, but not forward button.
