### ISSUE TITLE
The method 'inheritFromWidgetOfExactType' was called on null

### ISSUE THREAD

**Issue by huanggengzhong** [lukepighetti/fluro#168]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lukepighetti** [comment]
Unable to reproduce.

**Comment by lukepighetti** [comment]
Resolved by https://github.com/lukepighetti/fluro/pull/191
