### ISSUE TITLE
Adding a transition animation does not take effect

### ISSUE THREAD

**Issue by longzc1314** [lukepighetti/fluro#171]
static void push(BuildContext context, String path,
      {bool replace = false, bool clearStack = false}) {
    unfocus();
    Application.router.navigateTo(context, path,
        replace: replace,
        clearStack: clearStack,
        transitionDuration: Duration(milliseconds: 4),
        transition: TransitionType.inFromBottom);

**Comment by lukepighetti** [comment]
Cannot reproduce this issue.
