### ISSUE TITLE
ambiguous class name "Router" in Flutter 1.20 (and maybe earlier)

### ISSUE THREAD

**Issue by falkorichter** [lukepighetti/fluro#173]
**Describe the bug**
I upgraded to Flutter 1.20 and there is a name collision:

```
error: The name 'Router' is defined in the libraries 'package:fluro/src/router.dart (via package:fluro/fluro.dart)' and 'package:flutter/src/widgets/router.dart (via package:flutter/widgets.dart)'. (ambiguous_import at [flutter_door_buzzer] lib/src/routes.dart:6)
error: The name 'Router' is defined in the libraries 'package:fluro/src/router.dart (via package:fluro/fluro.dart)' and 'package:flutter/src/widgets/router.dart (via package:flutter/widgets.dart)'. (ambiguous_import at [flutter_door_buzzer] lib/src/routes.dart:6)
```

**To Reproduce**
1. Go to [github.com/falkorichter/open-taffeta-mobile-app/tree/macos](https://github.com/falkorichter/open-taffeta-mobile-app/tree/macos)
2. run `./flutterw build apk` or any other build command

**Expected behavior**
It should build

**Screenshots**
![image](https://user-images.githubusercontent.com/50506/90610868-514e7980-e206-11ea-93c1-71198fc2cfba.png)

**Desktop (please complete the following information):**

**Comment by jessejay247** [comment]
Having same issue, no error for flutter channel stable, but I'm using it for the web, i.e channel beta, and it's there.

**Comment by falkorichter** [comment]
@jessejay247 here is the class https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/router.dart#L233

If it´s not released yet, good - more of a reason to act here not to have a conflict once it´s out.

**Comment by Nashua354** [comment]
A simple hack I used is specify the import like this
`import 'package:fluro/fluro.dart' as route;`
and use `Router()` as `route.Router()`

**Comment by lukepighetti** [comment]
Resolved by https://github.com/lukepighetti/fluro/commit/a96fb1393c16bbbd0022b602c85c194eaa144f60

**Comment by mlkui** [comment]
You should use FluroRouter instead of Router to distinguish fluro's Router with the Router of flutter/src/widgets/router.dart

**Comment by lukepighetti** [comment]
We do.

**Comment by huynguyennovem** [comment]
- Look this: https://github.com/lukepighetti/fluro/blob/master/CHANGELOG.md#164

```
Rename Router to FluroRouter to avoid namespace collisions with the Router class from the new Pages / Navigator 2.0 API.
```

- Two solutions:
1. Change  `import 'package:flutter/material.dart';` with `import 'package:flutter/material.dart' hide Router;`
2. Upgrade fluro version to **>= 1.6.4**. Then replace all `Router` to `FluroRouter`

**Comment by jinjilynn** [comment]
why the fluro name the same name, if didn't, many problems can be avoid

**Comment by lukepighetti** [comment]
This problem was fixed months ago. Update your Fluro version.
