### ISSUE TITLE
I suggest the params not put in path

### ISSUE THREAD

**Issue by xukai59740** [lukepighetti/fluro#174]
```
router.navigateTo( context, "/home?fromLogin=yes", transition: TransitionType.native);
```
why we must put the params in path?
Disadvantages: 
1. It is difficult to transfer complex structure data (the amount of data is small, but the structure is complex)
2. `/?type=1` A parsing error occurred in `tree.matchRoute()`

**Comment by lukepighetti** [comment]
This is going to be a wontfix for `fluro 1.x.x`. However, you can now push custom RouteSettings with FluroRouter due to https://github.com/lukepighetti/fluro/commit/acfa58054765484489e49fd1f74a45002825fdcb

**Comment by wangbf11** [comment]
=



> 这将是 的一个修复`fluro 1.x.x`。但是，由于 acfa580，您现在可以`RouteSettings`推送[自](https://github.com/lukepighetti/fluro/commit/acfa58054765484489e49fd1f74a45002825fdcb)`FluroRouter.navigateTo`定义[](https://github.com/lukepighetti/fluro/commit/acfa58054765484489e49fd1f74a45002825fdcb)

这个方式RouteSettings 传递参数 每次弹框 都会 会触发页面重新加载，怎么处理呢
