### ISSUE TITLE
Why the parameter type of HandlerFunc is List<String>

### ISSUE THREAD

**Issue by evansherry** [lukepighetti/fluro#177]
I don't understand why the value of parameters is of type List<String>, which leads me to use a lot of parameters[0], isn't it better to use String type?

Hope to tell me, I am a little confused.

**Comment by evansherry** [comment]
I don't think it is necessary to add multiple values of key to the path

**Comment by lukepighetti** [comment]
Fluro `1.x.x` handles multiple instances of the same key


`/users/create?name=luke&phrase=hello%20world&number=7&number=10&number=13`

becomes:

```
"name": ["luke"],
"phrase": ["hello world"],
"number": ["7", "10", "13"],
```
