### ISSUE TITLE
Fluro 2.1.0

### ISSUE THREAD

**Issue by radvansky-tomas** [lukepighetti/fluro#181]
Hi everyone ;) I forked this plugin and added some interesting parts, merged some PRs etc and was planning to release it to public soon followed by some medium article.

However with new release of Navigator 2.0 https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade is all pretty obsolete.

So if anyone wants to look, feel free
https://github.com/radvansky-tomas/fluro.git

**Comment by lukepighetti** [comment]
Thanks Tomas, really appreciate you sharing this with us. I'm going to close this since there's nothing actionable on our end. Thanks!
