### ISSUE TITLE
flutter 1.22

### ISSUE THREAD

**Issue by lmr520** [lukepighetti/fluro#183]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

The name 'Router' is defined in the libraries 'package:fluro/src/router.dart (via package:fluro/fluro.dart)' and 'package:flutter/src/widgets/router.dart'.
Try using 'as prefix' for one of the import directives

**Comment by john990** [comment]
We also encountered the same problem, please adapt to the latest version of flutter, thank you.

**Comment by john990** [comment]
I found this, and it worked!
https://github.com/flutter/flutter/issues/64367#issuecomment-683374702

**Comment by lmr520** [comment]
ok I did up  your classname
![image](https://user-images.githubusercontent.com/39985568/95966812-28c9b100-0e3e-11eb-8db3-8fcd4bb47feb.png)

**Comment by lukepighetti** [comment]
For the time being you can use these temporary workarounds.

`import 'package:flutter/material.dart' hide Router;`
`import 'package:fluro/fluro.dart' as Fluro;`

**Comment by lukepighetti** [comment]
https://github.com/lukepighetti/fluro/commit/a96fb1393c16bbbd0022b602c85c194eaa144f60
