### ISSUE TITLE
Flutter Web - back button falls back to default handler

### ISSUE THREAD

**Issue by jaxnz** [lukepighetti/fluro#187]
I have an app where external users visit a URL with a custom parameter, but if they hit the back button it pops to the default router `'/'` in this case, it's the login screen for the admin to access the dashboard. 

```
class FluroRouter {
  static Router router = Router();
  static void setupRouter() {
    router.define('/', handler: _loginHandler);
    router.define('/online-enquiry/:id', handler: _onlineEnquiryHandler);
  }

  static Handler _loginHandler = Handler(handlerFunc: (context, Map<String, dynamic> params) => AuthStream());
  static Handler _onlineEnquiryHandler = Handler(handlerFunc: (context, Map<String, dynamic> params) => WebFormRoute(inputParameter: params['id'].first));
}
```

From what I can gather this is a Flutter issue? But I was wondering whether there is a work around? Otherwise I can move the login page handler to /login

**Comment by lukepighetti** [comment]
I believe this is a Flutter issue. Stuff like this is going to be a wontfix for `1.x.x`. Need to dig into the Nav 2.0 API more to see what's available to handle these situations in the next major release.
