### ISSUE TITLE
Route definition order affects route matching with named segments

### ISSUE THREAD

**Issue by arnemolland** [lukepighetti/fluro#188]
Hi, and thanks for breathing life into Fluro!

I've seen the internal matching algorithm inconsistently matching routes in one of our projects @dnb-asa. Debugging led me to this observation:

Route components are _sometimes_ evaluated as named segments depending in which order the routes are defined.

In our case, we have two routes with common components:
* `payments/recipients/new`
* `payments/recipients/:id/edit`

Whenever the `/new` path is defined first, the router matches the path and navigates to the correct route, while `/:id/edit` works as intended as well. If the `/:id/edit` path is defined before `/new`, the router tries to evalute `new` as the `:id` parameter and finds no routes for the node. While it's a simple action to refactor the paths to avoid a collision, the behaviour is inconsistent and might lead to confusion as it did in my case. If it's intended behaviour maybe it should be documented somewhere?

**Comment by lukepighetti** [comment]
This is not intended but it's also going to be a wontfix for `1.x.x` unless someone can provide a PR. Reason being that I don't believe this is a blocker (please tell me if it is) and I'm investing in migrating to Nav 2.0, and we'll have to see how that nets out.
