### ISSUE TITLE
the reverseTransitionDuration params is not found for PageRouteBuilder 

### ISSUE THREAD

**Issue by YufengHu123** [lukepighetti/fluro#190]
flutter version 

    • Flutter version 1.20.2 at /Library/flutter
    • Framework revision bbfbf1770c (10 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

Xcode's output:
↳
/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluro-1.7.4/lib/src/fluro_router.dart:223:11: Error: No named parameter with the name 'reverseTransitionDuration'.
          reverseTransitionDuration: transition == TransitionType.none
          ^^^^^^^^^^^^^^^^^^^^^^^^^
/Library/flutter/packages/flutter/lib/src/widgets/pages.dart:60:3: Context: Found this candidate, but the arguments don't match.
  PageRouteBuilder({
  ^^^^^^^^^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code

If I remove these lines of code

**Comment by YufengHu123** [comment]
if I remove thsee lines of code in fluro_router.dart it  starting to get normal
![image](https://user-images.githubusercontent.com/16814072/96808680-e01c8400-144b-11eb-9913-180396c3af55.png)

**Comment by YufengHu123** [comment]
this i change

**Comment by YufengHu123** [comment]
this i change

 return PageRouteBuilder<dynamic>(
          settings: routeSettings,
          maintainState: maintainState,
          pageBuilder: (BuildContext context, Animation<double> animation,
              Animation<double> secondaryAnimation) {
            return handler.handlerFunc(context, parameters);
          },
          transitionDuration: transition == TransitionType.none
              ? Duration.zero
              : transitionDuration ?? route.transitionDuration,
//  change 
//          reverseTransitionDuration: transition == TransitionType.none
//              ? Duration.zero
//              : transitionDuration ?? route.transitionDuration,
          transitionsBuilder: transition == TransitionType.none
              ? (_, __, ___, child) => child
              : routeTransitionsBuilder,
        );

**Comment by kcqnly** [comment]
I have the same problem as you, but I haven't used reverseTransitionDuration.

**Comment by longsan1234567** [comment]
报错 各位怎么解决的？？？？
../../../../Documents/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluro-1.7.4/lib/src/fluro_router.dart:223:11: Error: No named parameter with the name 'reverseTransitionDuration'.
          reverseTransitionDuration: transition == TransitionType.none
          ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Documents/development/flutter/packages/flutter/lib/src/widgets/pages.dart:60:3: Context: Found this candidate, but the arguments don't match.
  PageRouteBuilder({
  ^^^^^^^^^^^^^^^^

**Comment by lukepighetti** [comment]
This looks like it was a breaking change that I introduced in `1.7.3` but they should be resolved by https://github.com/lukepighetti/fluro/pull/189 in pub version `1.7.5` which is now available. Please re-open if this issue is not resolved.

**Comment by lukepighetti** [comment]
Did a little more work in https://github.com/lukepighetti/fluro/commit/8e3fd03fc1591ca50efced15c7218d538fa0af24 and released as `1.7.6`

**Comment by lukepighetti** [comment]
I think I misunderstood this issue. What channel are you on?

**Comment by lukepighetti** [comment]
Channel stable is `1.22.2` and this issue doesn't exist on that channel. This feature was added to Flutter recently so make sure you're up to date.
