### ISSUE TITLE
define route error

### ISSUE THREAD

**Issue by shifengbin** [lukepighetti/fluro#193]
Compiler message:
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn%2547/fluro-1.7.7/lib/src/fluro_router.dart:214:11: Error: No named parameter with the name 'reverseTransitionDuration'.
          reverseTransitionDuration: transition == TransitionType.none
          ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/widgets/pages.dart:52:3: Context: Found this candidate, but the arguments don't match.
  PageRouteBuilder({
  ^^^^^^^^^^^^^^^^

Is it not support new flutter version?

**Comment by liuxiaobina** [comment]
me too

**Comment by liuxiaobina** [comment]
me too      ,   updated   v1.7.6

**Comment by lukepighetti** [comment]
Closing as duplicate of https://github.com/lukepighetti/fluro/issues/190

**Comment by getpu** [comment]
> Compiler message:
> ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn%2547/fluro-1.7.7/lib/src/fluro_router.dart:214:11: Error: No named parameter with the name 'reverseTransitionDuration'.
> reverseTransitionDuration: transition == TransitionType.none
> ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../flutter/packages/flutter/lib/src/widgets/pages.dart:52:3: Context: Found this candidate, but the arguments don't match.
> PageRouteBuilder({
> ^^^^^^^^^^^^^^^^
> 
> Is it not support new flutter version?

yes, version 1.20 , i have equal question, update version 1.22.2 stable to solve the problem.
