### ISSUE TITLE
Url in the mobile browser is reset to home

### ISSUE THREAD

**Issue by paddyzab** [lukepighetti/fluro#194]
Hey Fluro team!

I have an issue I cannot easily debug and I hope that you will give me some tips how to understand what happens.

I have a simple web project, which is using parameterized urls to provide custom entry points to the application.
Let's say I have three paths:
`/hello`
`/venues` <- this request can be parameterized by appending `?venue_id=1`
`/goodbye`

For reasons unknown to me when I call `/venues?venue_id=1`, view is correctly configured, my api is being called and this particular view is being displayed, but, here is the part I need your help with,
My path is being reset to root i.e. `localhost:5000/#/`, I tested it with `firebase serve` as well `local_ip:5000/#/`, but only for parameterized path the path is still being reset.

Where would you suggest to look to find root cause of this issue?
Suspect: I am using ChangeNotifierProvider to handle async network operation. 

![fluro](https://user-images.githubusercontent.com/101805/98025144-9e0b1f00-1e09-11eb-9ba3-91ed21fbc65d.gif)

**Comment by lukepighetti** [comment]
Does this problem exist with the default router?

**Comment by paddyzab** [comment]
Hey Luke,

Here how I use it:
```
class Application {
    static FluroRouter router; // - router points to the package:fluro/fluro.dart
  }
```


later in the main component code I configure it in the following way:
```
class _AppComponentState extends State<AppComponent> {
    final router = FluroRouter(); // fluro router from fluro:fluro.dart
    Routes.configureRoutes(router);
    Application.router = router;
  }
```
I think I took this pattern from the example package directly.

**Comment by lukepighetti** [comment]
I am unable to reproduce this with Fluro or the default router. It's possible that you have a state issue somewhere, such as rebuilding the entire tree unintentionally.

Feel free to reopen this if you put together an MVCE.

```dart
import 'package:fluro/fluro.dart';
import 'package:flutter/material.dart';

void main() {
  FluroRouter.appRouter
    ..define('/',
        handler: Handler(
          handlerFunc: (context, params) => MyHomePage(title: "/"),
        ))
    ..define('/foo',
        handler: Handler(
          handlerFunc: (context, params) => MyHomePage(title: "/foo"),
        ));

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      onGenerateRoute: FluroRouter.appRouter.generator,
      // routes: {
      //   "/": (context) => MyHomePage(title: "/"),
      //   "/foo": (context) => MyHomePage(title: "/foo"),
      // },
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              widget.title,
            ),
          ],
        ),
      ),
      floatingActionButton: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          FlatButton(
            onPressed: () => Navigator.of(context).pushNamed('/'),
            child: Text('/'),
          ),
          FlatButton(
            onPressed: () => Navigator.of(context).pushNamed('/foo'),
            child: Text('/foo'),
          ),
        ],
      ),
    );
  }
}
```

**Comment by paddyzab** [comment]
You were spot on.
After refactoring the app to use less violent widget as a async operation consumer, the url is not mutated.

Thanks man!

**Comment by surveshoeb** [comment]
@paddyzab can you let me know how did you solve this issue?

**Comment by paddyzab** [comment]
> @paddyzab can you let me know how did you solve this issue?

Hey @surveshoeb, If remember correctly following luke's suggestion of refactoring state out.
This way path was persisted across the calls to the router.

If you have code visible on GH send me the link to the repo will take a look with you into that.

cheers,

**Comment by surveshoeb** [comment]
@paddyzab thanks for the reply. I have fixed my issue, it was due to the `Future.delayed` used on the startup screen which redirects to the dashboard screen after 5sec. Removing the delay on the web got it working.
