### ISSUE TITLE
1.7.7 cannot be used in flutter 1.20.3

### ISSUE THREAD

**Issue by dashenxiwo** [lukepighetti/fluro#197]
I can't compile it
pub.flutter-io.cn/fluro-1.7.7/lib/src/fluro_router.dart:214:11: Error: No named parameter with the name 'reverseTransitionDuration'.
          reverseTransitionDuration: transition == TransitionType.none  
          ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Linykun** [comment]
I ran into the same problem.

**Comment by lukepighetti** [comment]
Closed as duplicate of https://github.com/lukepighetti/fluro/issues/190#issuecomment-714425580
