### ISSUE TITLE
Error: No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by pinpong** [lukepighetti/fluro#200]
`Error: No named parameter with the name 'nullOk'.
Navigator.of(context, rootNavigator: rootNavigator, nullOk: nullOk);`

https://github.com/flutter/flutter/commit/de884f1afe1daa12def5ecaa08ab03e6af406d39

Flutter 1.24.0-8.0.pre.356 • channel master • https://github.com/flutter/flutter.git
Framework • revision e6bd95bc5c • 2020-11-23 14:10:58 -0800
Engine • revision 23a8e027db
Tools • Dart 2.12.0 (build 2.12.0-62.0.dev)

**Comment by lukepighetti** [comment]
Thanks for the contribution!
