### ISSUE TITLE
Why is this better

### ISSUE THREAD

**Issue by ajaygautam** [lukepighetti/fluro#204]
Hello

A request for a bit more documentation. Being new to Flutter & navigation... wondering how this is worthy replacement for the default navigator. Can you please add information to that effect - to the README?

Thanks

Ajay

**Comment by lukepighetti** [comment]
A little context: this package has been around for a verrrrrrrry long time. Back when it was first created the default navigator (Nav 1.0) was missing a lot of features. This package filled in the gaps and brought a lot to the table.

So back to your question: what does `fluro` provide now? 

The short answer is that `fluro` makes it easy to extract parameters from the navigator path. This is especially useful for deeplinking. You can also define transitions when you define your routes. You can also access your root navigator without context.

Now, if your reaction is "so what," then I would definitely recommend using the default navigator. It works great. But, if any of those things are valuable to you, use `fluro`.

Looking forward, now that Navigator 2.0 has been released, it is top priority to rebuild `fluro` to use this new API, and it will almost certainly fundamentally change the way `fluro` works and what problems it solves.

**Comment by lukepighetti** [comment]
I'm going to close this and pin it.

**Comment by ajaygautam** [comment]
Thanks for the details. 
the context does help 👍
