### ISSUE TITLE
Null safety (NNBD)

### ISSUE THREAD

**Issue by lukepighetti** [lukepighetti/fluro#205]
We should probably migrate 1.x to non-nullable by default as a hotfix.

**Comment by lukepighetti** [comment]
1.x will be migrated to null safety before work on 2.0 begins.

**Comment by lukepighetti** [comment]
Null-safe version is available as a git dependency here: https://github.com/lukepighetti/fluro/tree/null-safety

**Comment by lukepighetti** [comment]
Related: https://github.com/dart-lang/sdk/issues/41398#issuecomment-770467724

**Comment by lukepighetti** [comment]
Just a quick comment on stability.

I was going to wait until we did the Navigator 2.0 rewrite to offer null safety. I decided to do a quick port for 1.x to null safety. If you need to stay on 1.x and you need null safety, use the git dependency. If you're not in a hurry, wait for the fluro 2.0 with navigator 2.0 release which will be a complete rewrite with null safety.

**Comment by muhlba91** [comment]
@lukepighetti any timeline for 2.0 or would it be possible to release 1.x nnbd as a pre-release version as well in the meantime?

**Comment by lukepighetti** [comment]
Let me revisit this early this coming week

**Comment by lukepighetti** [comment]
The null safe version of Fluro is now available as `2.0.2` on pub.
