### ISSUE TITLE
Tab bar view / Flows

### ISSUE THREAD

**Issue by lukepighetti** [lukepighetti/fluro#211]
Sub-routable collections of pages like a tab bar view or an onboarding flow. Can have fixed elements like a common app bar or overlays.

**Comment by lukepighetti** [comment]
Tracking for fluro 2.0

**Comment by Wissperwind** [comment]
Hi,
I need exactly that! Have you seen this stackoverflow post?
https://stackoverflow.com/questions/61850247/flutter-web-navigation-with-persistent-drawer-and-appbar
It was viewed more than 1000 times.
Are you working on a possibility to have Flutter Web Navigation with persistent drawer and appbar?

**Comment by lukepighetti** [comment]
That would be ideal, yes.
