### ISSUE TITLE
navigateTo() can ignore the introduced duration without warning about it

### ISSUE THREAD

**Issue by lsalazarm99** [lukepighetti/fluro#216]
Context: A login screen. The login button does [this](https://medium.com/flutter-community/flutter-fab-navigation-animation-to-next-screen-f63acf3de6b7) animation in order to go to Home Route.

Having this in my Login Button's `onTap`:
```dart
....

getRouter().navigateTo(
        context,
        homeRoute,
        transition: TransitionType.custom,
        transitionDuration: Duration(seconds: 5),
        transitionBuilder: (context, animation, secondaryAnimation, child) {...},
);
```

Router file:
```dart
const homeRoute = '/home';
....

Handler homeHandler = Handler(
  handlerFunc: (_, __) => HomeRoute(),
);
....

FluroRouter getRouter() {
  var router = FluroRouter();

  router.define(
    homeRoute,
    handler: homeHandler,
  );

  .... more routes

  return router;
}
```

`navigateTo` does this:
```dart
Future navigateTo(BuildContext context, String path,
      {bool replace = false,
      bool clearStack = false,
      bool maintainState = true,
      bool rootNavigator = false,
      TransitionType? transition,
      Duration? transitionDuration,
      RouteTransitionsBuilder? transitionBuilder,
      RouteSettings? routeSettings}) {
    RouteMatch routeMatch = matchRoute(context, path,
        transitionType: transition,
        transitionsBuilder: transitionBuilder,
        transitionDuration: transitionDuration, // It is only used here
        maintainState: maintainState,
        routeSettings: routeSettings);

    ....
}
```

And `matchRoute` does this:
```dart
RouteMatch matchRoute(BuildContext? buildContext, String? path,
      {RouteSettings? routeSettings,
      TransitionType? transitionType,
      Duration? transitionDuration,
      RouteTransitionsBuilder? transitionsBuilder,
      bool maintainState = true}) {
    RouteSettings? settingsToUse = routeSettings;
    if (routeSettings == null) {
      settingsToUse = RouteSettings(name: path);
    }
    if (settingsToUse!.name == null) {
      settingsToUse = settingsToUse.copyWith(name: path);
    }
    AppRouteMatch? match = _routeTree.matchRoute(path!);
    AppRoute? route = match?.route;

    if (route?.transitionDuration != null) {
      transitionDuration = route?.transitionDuration; // It is overriden here
    }

    ....
}
```

As you can see, `transitionDuration` can be overridden if `route?.transitionDuration` is not `null`. I'm not sure if this is the desired behavior, but if I'm passing a `transitionDuration` to `navigateTo`, shouldn't it prefer that value instead of the default one?

By the way, the default one is the defined here:
```dart
router.define(
  homeRoute,
  handler: homeHandler,
  transitionDuration: null, // Here
);
```

I could leave it as `null`. In that case, it will use the value I pass to `navigateTo`, but as you can imagine I will have to specify a duration every time I want to go to `homeRoute` (unless I want it to have no duration so no animation, which I don't think it's a common case).

Fluro version: "null-safety" version,  but it happens in 1.7.8 too.

**Comment by lukepighetti** [comment]
If you specify a transitionDuration explicitly it should override any defaults. I won't be able to get to this anytime soon because I'm working on Fluro 2.0, but a pull-request would be appreciated. It looks like you've already solved the problem.

**Comment by lsalazarm99** [comment]
Great!
PR #219

**Comment by lukepighetti** [comment]
Closing this due to no-op PR and no follow up. Nothing actionable on my end. Reopen if necessary. Thanks for the contribution!
