### ISSUE TITLE
how to return value back when pop

### ISSUE THREAD

**Issue by function2000** [lukepighetti/fluro#225]
For example:
First page:
Navigator.of(context).pushNamed('/router/second').then((value) {
                    // dialog to display the value return
                    _showDialog(context, value);
                  })

Second page:
Navigator.of(context).pop('this is the value return to first page');

How to do this via Fluro?  Thanks!

**Comment by lukepighetti** [comment]
We wrap the Flutter Navigator so you can still use all the core Navigator APIs to perform these types of tasks
