### ISSUE TITLE
How to use Fluro with bottom navigator?

### ISSUE THREAD

**Issue by Dhruvi16** [lukepighetti/fluro#231]
## Description
I am aware of the concept that with the Bottom navigation bar we will need to set up a different Navigator. And I am not sure how to do that. Can anyone please help with how to do it?

**Comment by Siqlain-Hanif** [comment]
Idk how fluro can help in this case what i am doing is having a main screen with pageView that has pageController. And i am using bottomNavigation bar buttons to change the current index of page controller

**Comment by lukepighetti** [comment]
This is a limitation of the Flutter Navigator 1.0, which we are controlling with Fluro.
