### ISSUE TITLE
plz update  the  example with null safety 

### ISSUE THREAD

**Issue by samithe7** [lukepighetti/fluro#232]
}The argument type 'Widget? Function(BuildContext, Map<String, List<String>>)' can't be assigned to the parameter type 'Widget? Function(BuildContext?, Map<String, List<String>>)'.

**Comment by jackypan1989** [comment]
```
Handler defaultHandler = Handler(
    handlerFunc: (BuildContext? context, Map<String, List<String>> params) {
  return YourPageComponent();
});
```

**Comment by treeder** [comment]
I think this might be useful, I had this issue: https://github.com/lukepighetti/fluro/issues/227#issuecomment-827667343
