### ISSUE TITLE
 I found a very magical bug. When I use fluro to jump, the text element of the page will be copied as red and yellow borders.

### ISSUE THREAD

**Issue by yehoan** [lukepighetti/fluro#277]
![image](https://user-images.githubusercontent.com/22631753/207954246-7cdd1adb-bc7d-4380-908d-0a31bd07e46e.png)
![image](https://user-images.githubusercontent.com/22631753/207954385-4ac77e01-c040-45dc-b5eb-60ea216b3b17.png)

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/207954495-80c48df1-4aab-4a39-9288-31a49a85e116.png)

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/207954593-e9e349ed-e727-4424-9f44-55dae8a038e1.png)
At first I thought it was caused by my global configuration or some elements were not set, but I didn’t find this when I directly opened a certain route. For example, when I directly configured the class of the personal center in main.dart, everything was normal, but I used Application.router
        .navigateTo(context, '/', transition: TransitionType.fadeIn); It appeared again. I searched all over the tutorials and API, but I didn't find this problem. So I want to ask why this is the case

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/207955166-76c74572-1e70-466b-8e6b-9837c1336a53.png)

**Comment by lukepighetti** [comment]
Wrap it in Scaffold or Material
