### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by abdulkash** [lukepighetti/fluro#279]
Error: The method 'copyWith' isn't defined for the class 'RouteSettings'.
fluro_router.dart:114
- 'RouteSettings' is from 'package:flutter/src/widgets/navigator.dart' ('../../../Downloads/Dev%20files/flutter_windows_3.0.5-stable/flutter/packages/flutter/lib/src/widgets/navigator.dart').
navigator.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
      settingsToUse = settingsToUse.copyWith(name: path);

**Comment by lukepighetti** [comment]
2.0.5

**Comment by abdulkash** [comment]
thanks 😊
