### ISSUE TITLE
Passing in contextual params

### ISSUE THREAD

**Issue by seenickcode** [lukepighetti/fluro#49]
Hello there,

I have a class that I'd like to navigate to, defined by a Flurio handler, like so:

```
...
myFluroRouter.define('/foobars/:id/edit', handler: new Handler(
        handlerFunc: (BuildContext context, Map<String, dynamic> params) {
      final String id = params['id']?.first;

      return new FoobarEdit(new Key(id), int.parse(id));
    }));
```

What I'd like to do now is be able to pass in a callback to `FoobarEdit`. This callback is contextual and depends on the class that is invoking the constructor for this class, like so:

 ```
...
myFluroRouter.define('/foobars/:id/edit', handler: new Handler(
        handlerFunc: (BuildContext context, Map<String, dynamic> params) {
      final String id = params['id']?.first;

      return new FoobarEdit(new Key(id), int.parse(id), myFoobarCallbackFunc);
    }));
```

What do you think the best approach for this is?  It seems like for now, I'm forced to use the traditional 
 Flutter `Navigate` class like so:

```
Navigator.push(
        context, new MaterialPageRoute(builder: (context) => new FoobarEdit(...));
```

Is there a better way to do this?

**Comment by lukepighetti** [comment]
You can now pass custom RouteSettings with arguments https://github.com/lukepighetti/fluro/commit/acfa58054765484489e49fd1f74a45002825fdcb

**Comment by lukepighetti** [comment]
Wow, I totally did not triage this properly. @seenickcode is this something you're still looking for? Feel free to reopen if it is.
