### ISSUE TITLE
Support Chinese characters in routes

### ISSUE THREAD

**Issue by zhujian1989** [lukepighetti/fluro#53]
error：
flutter: /demo?message=测试&color_hex=#F76F00
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown while handling a gesture:
flutter: Invalid argument(s): Illegal percent encoding in URI
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _Uri._uriDecode (dart:core/uri.dart:2835:11)
flutter: #1      Uri.decodeComponent (dart:core/uri.dart:1109:17)

**Comment by zhujian1989** [comment]
change like this 
the problem is solved
/demo?message=%E6%B5%8B%E8%AF%95&color_hex=#F76F00

**Comment by lblblong** [comment]
@zhujian1989 I have also encountered this problem, turned over the darts document, did not find a way to convert Chinese into a percent sign, how do you convert it?

**Comment by Nealyang** [comment]
@lblblong  I have encountered this problem too; how to convert Chinese into a percent sign?

**Comment by Nealyang** [comment]
@lblblong  Uri.encodeComponent

**Comment by lukepighetti** [comment]
Tracking for Fluro 2.0
