### ISSUE TITLE
Nested Routes

### ISSUE THREAD

**Issue by ragasubekti** [lukepighetti/fluro#60]
Hi! Is it possible to do Nested Route in Fluro?

**Comment by gedw99** [comment]
I also need this :)

**Comment by lukef** [comment]
Can you describe a use case for nested routes?

**Comment by ragasubekti** [comment]
screen with always the same scaffold, and login/register screen?

**Comment by shikelong** [comment]
Is it possible now?

**Comment by proghjy** [comment]
@lukef Here is a good [example](https://github.com/bizz84/nested-navigation-demo-flutter).

**Comment by delizondo** [comment]
I also need this, in my "main" view I have a Navigator like this:

```Container(
      child: Center(
        child: Navigator(          
          onGenerateRoute: router.generator,
          initialRoute: HOME,
        ),
      ),
    );
  ```
And I want to replace just the content inside the Navigator widget, but then I try to navigate with Fluro, it replaces the whole screen.

**Comment by Aerofluxx** [comment]
Also following this for an update. Nested navigator for the web, without reloading the whole page, is also my goal. Keeping alive parts like the drawer or an list of orders (in my case) would be awesome.

**Comment by lukepighetti** [comment]
This is now the official tracking issue for nested routing. We will be investigating this when we migrate to the new Pages / Navigator 2.0 API.

**Comment by gibahjoe** [comment]
Any updates on this? Does anyone have any temporary workaround that works?

**Comment by lukepighetti** [comment]
When Fluro 2.0 is released I will give a full update for the community. This feature won't make it into `1.x`

**Comment by chimon2000** [comment]
@lukepighetti is there a time frame for 2.0?

**Comment by lukepighetti** [comment]
There is no scheduled release date for explicit time frame for 2.0.

**Comment by tananga** [comment]
Hi. Any update on that? I want to add nasted routing like this one.

![Screenshot 2022-02-15 at 08 10 22](https://user-images.githubusercontent.com/44244477/154010850-d59691bf-1efb-4353-8556-92760fe6e60e.png)
