### ISSUE TITLE
Listening to Route events

### ISSUE THREAD

**Issue by Solido** [lukepighetti/fluro#7]
I'd like to register to Route events using didChangeNext for example but they can only be accessed by overriding. Is there a way to configure and pass my own routes ? 
If I understand clearly, currently RouteCreator constrain to only MaterialPageRoute or PageRouteBuilder so I cannot override Route listeners.
Thank you for any clarification.

**Comment by lukef** [comment]
I'm experimenting with a `Routable` interface that could be used to to connect a widget to push and pop events. Flutter also has a `navigationObserver` property on `MaterialApp` that can be used generically. If you're interested you can look at the `https://github.com/goposse/fluro/tree/routable` branch. Feedback appreciated.

**Comment by lukef** [comment]
Flutter has the route observer concept which can be used to listen for push and pop events. I'd love to have a more integrated solution for this in the long run but I suspect it'll require some customization at the root level so will probably be a 2.0 thing.

**Comment by lukepighetti** [comment]
Please use the Flutter route observer for the duration of fluro `1.x.x`, in other words this is a wontfix for `1.x.x`
