### ISSUE TITLE
Modals / Dialogs

### ISSUE THREAD

**Issue by winsonet** [lukepighetti/fluro#76]
I created a popup class inherit the ModalRoute, but I don't know how to use with fluro, I tried to add in route handler, but it said the return object is not a widget, but if I just use `Navigator.push` and everything is ok.

and I also want to know how can I use the `type:HandlerType.route` option?

thanks!

**Comment by qq125183592** [comment]
I also need it.

**Comment by lukepighetti** [comment]
This is the official issue for supporting Modals and Dialogs. We will be investigating this when we migrate to Pages / Navigator 2.0 API.

**Comment by abegehr** [comment]
Since `showModalBottomSheet()` is not supported for fluro's route paths with parameters atm, I have created a workaround overwriting `onGenerateRoute()` and using a custom `PageRouteBuilder` with `Dismissable` to get a similar effect.
While it is not the same as `showModalBottomSheet()`, the following workaround supports translucent modal routes that can be dismissed by vertical swiping down, and open with animation swiping up:

```
  Route onGenerateRoute(RouteSettings settings) {
    final appRouteMatch = _router.match(settings.name);
    const translucentModalRoutePaths = [
      ViewPostScreen.routePath,
      CreatePostScreen.routePath,
    ];

    if (translucentModalRoutePaths.contains(appRouteMatch.route.route))
      return _buildTranslucentModalPageRoute(appRouteMatch);
    else
      return _router.generator(settings);
  }

  PageRouteBuilder _buildTranslucentModalPageRoute(
      AppRouteMatch appRouteMatch) {
    final params = appRouteMatch.parameters;
    final appRoute = appRouteMatch.route;
    final Handler handler = appRoute?.handler;

    return PageRouteBuilder(
        opaque: false,
        barrierDismissible: true,
        pageBuilder: (context, _, __) => Dismissible(
              direction: DismissDirection.vertical,
              key: Key(appRoute.route),
              onDismissed: (_) => Navigator.of(context).pop(),
              child: handler?.handlerFunc(context, params),
            ),
        transitionDuration: Duration(milliseconds: 250),
        transitionsBuilder: (context, anim, _, child) => SlideTransition(
              position: Tween<Offset>(
                begin: const Offset(0.0, 1.0),
                end: const Offset(0.0, 0.0),
              ).animate(anim),
              child: child,
            ));
  }
```

**Comment by lukepighetti** [comment]
Internal note: separate overlay stack for dialogs, outside of router tree?
