### ISSUE TITLE
Create Route With List

### ISSUE THREAD

**Issue by mamen2022** [lukepighetti/fluro#83]
Hi,

I have a question, not really a Issue. 
How can we pass a list of arguments in the route String ? 
Using the example app available, I have successfully implemented the Fluro plugin on my app for only one argument. Although, how can we pass a List of Strings to the Handler? In the example, the args are passed to the handler with `Map<String, List<String>>` params. 

If I have the route:
String route = "/demo?message=$message&color_hex=$hexCode";

The Map Gets:
message -> [$message]
color_hex -> [$hexCode]

But if I want my Map to be:
name -> [$first, $last]
age -> [$number]

How can I build the route? I tired so many things but with no success. Can someone help?

**Comment by lukepighetti** [comment]
You can do this `/demo?name=first&name=last`
