### ISSUE TITLE
Current route?

### ISSUE THREAD

**Issue by quetool** [lukepighetti/fluro#86]
Hi, I need to check in which route I am currently in. Is there a way to do this?
EDIT: I mean, the last route navigated to (the current route showed in screen, the last in the stack or tree)

**Comment by hasonguo** [comment]
> Hi, I need to check in which route I am currently in. Is there a way to do this?
> EDIT: I mean, the last route navigated to (the current route showed in screen, the last in the stack or tree)

Have you worked it out yet？I need that, too

**Comment by quetool** [comment]
> > Hi, I need to check in which route I am currently in. Is there a way to do this?
> > EDIT: I mean, the last route navigated to (the current route showed in screen, the last in the stack or tree)
> 
> Have you worked it out yet？I need that, too

Yep... I did it with a Route Observer

```
import 'package:flutter/material.dart';

class RouteObserverHelper extends RouteObserver<PageRoute<dynamic>> {
  var screenName = "";
  var previousScreenName = "";
  void _sendScreenView(PageRoute<dynamic> route, PageRoute<dynamic> previousRoute) {
    this.screenName = route.settings.name;
    if (previousRoute != null) {
      this.previousScreenName = previousRoute.settings.name;
    }
  }

  @override
  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    super.didPush(route, previousRoute);
    if (route is PageRoute && previousRoute is PageRoute) {
      _sendScreenView(route, previousRoute);
    }
  }

  @override
  void didReplace({Route<dynamic> newRoute, Route<dynamic> oldRoute}) {
    super.didReplace(newRoute: newRoute, oldRoute: oldRoute);
    if (newRoute is PageRoute && oldRoute is PageRoute) {
      _sendScreenView(newRoute, oldRoute);
    }
  }

  @override
  void didPop(Route<dynamic> route, Route<dynamic> previousRoute) {
    super.didPop(route, previousRoute);
    if (previousRoute is PageRoute && route is PageRoute) {
      _sendScreenView(previousRoute, route);
    }
  }
}

```

**Comment by hasonguo** [comment]
yeah,Thanks very much

**Comment by lukepighetti** [comment]
Closing because there is nothing actionable
