### ISSUE TITLE
avaiding context errors with navigatorKey

### ISSUE THREAD

**Issue by fluxsaas** [lukepighetti/fluro#89]
Hey,

sometimes i get the `Looking up a deactivated widget's ancestor is unsafe` error, when using `context` to navigate to a new route from e.g. redux actions.

i avoid this problem by using the `GlobalKey<NavigatorState>`.

Setup as following:

````dart
class Application {
  static Router router;
  static GlobalKey<NavigatorState> navigatorKey;
}
````

````dart
void main() async {
  final GlobalKey<NavigatorState> navigatorKey =
      new GlobalKey<NavigatorState>();
  Application.navigatorKey = navigatorKey;
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return StoreProvider(
      store: Application.store,
      child: new MaterialApp(
        debugShowCheckedModeBanner: false,
        onGenerateRoute: Application.router.generator,
        navigatorKey: Application.navigatorKey,
      ),
    );
  }
}
````

...and the routes defined similar to your example.

Navigating:

````dart
Application.navigatorKey.currentState
        .pushNamed('/someniceroute');
````

is this a preferable approach?

**Comment by lukepighetti** [comment]
Ah. This is interesting, and valid, but it's going to be a wontfix for `1.x.x`. I'm going to close this because I suspect this will be irrelevant after we migrate to Pages / Navigator 2.0.
