### ISSUE TITLE
[Enhancement] Add arguments support

### ISSUE THREAD

**Issue by Qwin** [lukepighetti/fluro#93]
Currently flutter only supports passing data through path, allow people as well to pass in arguments as underneath the covers you are calling Navigator. so you could basically add an optional parameter to NavigateTo to pass along the arguments parameter.

**Comment by my9074** [comment]
+1

**Comment by gsabater** [comment]
+2

**Comment by pdliuw** [comment]
> Currently flutter only supports passing data through path, allow people as well to pass in arguments as underneath the covers you are calling Navigator. so you could basically add an optional parameter to NavigateTo to pass along the arguments parameter.

Airoute supports this feature (Airoute : https://github.com/pdliuw/airoute)

**Comment by softmarshmallow** [comment]
i choose https://github.com/Flutterando/modular over fluro, primary reason is that fluro does not support passing arguments

**Comment by lukepighetti** [comment]
You can now pass custom RouteSettings with arguments https://github.com/lukepighetti/fluro/commit/acfa58054765484489e49fd1f74a45002825fdcb
