### ISSUE TITLE
when set TransitionType.fadeIn  iOS Swipe back not work，Android working fine

### ISSUE THREAD

**Issue by iusn** [lukepighetti/fluro#94]
Hi：
This is greate libary，but i have a problem。
When set TransitionType.fadeIn  iOS Swipe back not work，Android working fine

How to solve this problem？
Do you have any idea？
Thank you

**Comment by miguelpruivo** [comment]
That’s because the slide back on iOS is part of the `CupertinoTransition`.

**Comment by jiangyh1024** [comment]
@miguelpruivo 
you mean if we set transition type to 'cupertino', it can work both on android and ios?
![image](https://user-images.githubusercontent.com/34930870/82278811-a1c2fa80-99bd-11ea-8be3-cc5c91307f1a.png)

**Comment by jiangyh1024** [comment]
@miguelpruivo it worked on ios after I changed the transition type to 'cupertino'

**Comment by lukepighetti** [comment]
Closing because there is nothing actionable
